language: go

go:
- "1.10.x"
- master

install:
- make get-dev-deps

services:
- mongodb

env:
  global:

jobs:
  include:
    - stage: build
      script: make build

    - stage: test
      script: make lint
    - script: make test-with-coverage
      env: 
      - STORAGE_URL=mongodb://127.0.0.1:27017/
